language: cpp
sudo: required
compiler:
  - gcc
os:
  - linux
dist: trusty
before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y --force-yes sloccount cppcheck grep pyflakes findbugs
script:
  - ./scripts/2016/get_all_contents.sh
  - ./scripts/2017/get_all_contents.sh
